/* tslint:disable */
/* eslint-disable */
/**
 * Apimg
 * Apimg's API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { AddItem } from './add-item';
 /**
 * Request body to add customer items
 *
 * @export
 * @interface AddCustomerItemsRequest
 */
export interface AddCustomerItemsRequest {

    /**
     * List of items to add
     *
     * @type {Array<AddItem>}
     * @memberof AddCustomerItemsRequest
     */
    items: Array<AddItem>;
}
