/* tslint:disable */
/* eslint-disable */
/**
 * Apimg
 * Apimg's API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { V1customeruserUsers } from './v1customeruser-users';
 /**
 * Request body to add customer users
 *
 * @export
 * @interface AddCustomerUsersRequest
 */
export interface AddCustomerUsersRequest {

    /**
     * List of customer users
     *
     * @type {Array<V1customeruserUsers>}
     * @memberof AddCustomerUsersRequest
     */
    users: Array<V1customeruserUsers>;
}
