/* tslint:disable */
/* eslint-disable */
/**
 * Apimg
 * Apimg's API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { SubcategoryRequestItem } from './subcategory-request-item';
 /**
 * Request body to add customer subcategories
 *
 * @export
 * @interface AddCustomerSubcategoriesRequest
 */
export interface AddCustomerSubcategoriesRequest {

    /**
     * List of subcategories to add
     *
     * @type {Array<SubcategoryRequestItem>}
     * @memberof AddCustomerSubcategoriesRequest
     */
    subcategories?: Array<SubcategoryRequestItem>;
}
