/* tslint:disable */
/* eslint-disable */
/**
 * Apimg
 * Apimg's API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * Add Item content
 *
 * @export
 * @interface AddItem
 */
export interface AddItem {

    /**
     * The unique identifier for the subcategory
     *
     * @type {string}
     * @memberof AddItem
     * @example 1-1-1
     */
    subcategory_id?: string;

    /**
     * The name of the item
     *
     * @type {string}
     * @memberof AddItem
     * @example Nouvelle Aquitaine
     */
    name?: string;
}
