/* tslint:disable */
/* eslint-disable */
/**
 * Apimg
 * Apimg's API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * Category weight content
 *
 * @export
 * @interface CategoryWeight
 */
export interface CategoryWeight {

    /**
     * The unique identifier for the category
     *
     * @type {string}
     * @memberof CategoryWeight
     * @example 1-1
     */
    id?: string;

    /**
     * The new level number (weight)
     *
     * @type {number}
     * @memberof CategoryWeight
     * @example 5
     */
    level_number?: number;
}
