/* tslint:disable */
/* eslint-disable */
/**
 * Apimg
 * Apimg's API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * Category content
 *
 * @export
 * @interface Category1
 */
export interface Category1 {

    /**
     * The unique identifier for the category
     *
     * @type {string}
     * @memberof Category1
     * @example 1-1
     */
    id?: string;

    /**
     * The name of the category
     *
     * @type {string}
     * @memberof Category1
     * @example Category 1
     */
    category_name?: string;

    /**
     * The level number (weight) of the category
     *
     * @type {number}
     * @memberof Category1
     * @example 5
     */
    level_number?: number;
}
