/* tslint:disable */
/* eslint-disable */
/**
 * Apimg
 * Apimg's API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * Response body for creating customer user profile types
 *
 * @export
 * @interface CreateCustomerUserProfileTypesResponse
 */
export interface CreateCustomerUserProfileTypesResponse {

    /**
     * The unique identifier for the user profile type
     *
     * @type {string}
     * @memberof CreateCustomerUserProfileTypesResponse
     * @example 1-1
     */
    id?: string;

    /**
     * The name of the user profile type
     *
     * @type {string}
     * @memberof CreateCustomerUserProfileTypesResponse
     * @example Agency
     */
    type?: string;

    /**
     * List of category IDs used by the profile type
     *
     * @type {Array<string>}
     * @memberof CreateCustomerUserProfileTypesResponse
     * @example ["1-12-1","1-12-2"]
     */
    used_categories?: Array<string>;
}
