/* tslint:disable */
/* eslint-disable */
/**
 * Apimg
 * Apimg's API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * Request body to delete customer user profile types
 *
 * @export
 * @interface DeleteCustomerUserProfileTypesRequest
 */
export interface DeleteCustomerUserProfileTypesRequest {

    /**
     * The unique identifier for the user profile type
     *
     * @type {string}
     * @memberof DeleteCustomerUserProfileTypesRequest
     * @example 1-1
     */
    id: string;
}
