/* tslint:disable */
/* eslint-disable */
/**
 * Apimg
 * Apimg's API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * Request body to delete customer algorithm items
 *
 * @export
 * @interface DeleteCustomerAlgorithmItemsRequest
 */
export interface DeleteCustomerAlgorithmItemsRequest {

    /**
     * List of item IDs to be deleted
     *
     * @type {Array<string>}
     * @memberof DeleteCustomerAlgorithmItemsRequest
     * @example ["1-1-1-1","1-1-1-2","1-1-1-3"]
     */
    items_ids: Array<string>;
}
