/* tslint:disable */
/* eslint-disable */
/**
 * Apimg
 * Apimg's API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * Request body to delete customer subcategories
 *
 * @export
 * @interface DeleteCustomerSubcategoriesRequest
 */
export interface DeleteCustomerSubcategoriesRequest {

    /**
     * List of subcategory IDs to be deleted
     *
     * @type {Array<string>}
     * @memberof DeleteCustomerSubcategoriesRequest
     * @example ["1-12-1","1-12-2","1-12-3"]
     */
    categories_ids: Array<string>;
}
