/* tslint:disable */
/* eslint-disable */
/**
 * Apimg
 * Apimg's API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * Filter content
 *
 * @export
 * @interface Filter
 */
export interface Filter {

    /**
     * The unique identifier for the filter
     *
     * @type {string}
     * @memberof Filter
     * @example 1-3
     */
    id?: string;

    /**
     * The name of the filter
     *
     * @type {string}
     * @memberof Filter
     * @example Filter age in interval
     */
    name?: string;

    /**
     * The base score for the filter (optional)
     *
     * @type {number}
     * @memberof Filter
     * @example 50
     */
    base_score?: number | null;

    /**
     * The type of the filter
     *
     * @type {number}
     * @memberof Filter
     * @example 1
     */
    type?: number;

    /**
     * The subcategory ID concerned by the filter
     *
     * @type {string}
     * @memberof Filter
     * @example 1-12-1
     */
    subcategory_id?: string;

    /**
     * Subcategories to compare the user's items with (optional)
     *
     * @type {Array<string>}
     * @memberof Filter
     * @example ["1-12-2","1-12-4"]
     */
    compare_with?: Array<string> | null;
}
