/* tslint:disable */
/* eslint-disable */
/**
 * Apimg
 * Apimg's API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { GetCustomerDashboardDataResponseLastSuggestedMatchs } from './get-customer-dashboard-data-response-last-suggested-matchs';
import { GetCustomerDashboardDataResponseTops } from './get-customer-dashboard-data-response-tops';
import { GetCustomerDashboardDataResponseUsersIdsAndMetadata } from './get-customer-dashboard-data-response-users-ids-and-metadata';
 /**
 * Response body for customer dashboard data
 *
 * @export
 * @interface GetCustomerDashboardDataResponse
 */
export interface GetCustomerDashboardDataResponse {

    /**
     * @type {GetCustomerDashboardDataResponseTops}
     * @memberof GetCustomerDashboardDataResponse
     */
    tops?: GetCustomerDashboardDataResponseTops;

    /**
     * @type {Array<GetCustomerDashboardDataResponseLastSuggestedMatchs>}
     * @memberof GetCustomerDashboardDataResponse
     */
    last_suggested_matchs?: Array<GetCustomerDashboardDataResponseLastSuggestedMatchs>;

    /**
     * @type {Array<GetCustomerDashboardDataResponseUsersIdsAndMetadata>}
     * @memberof GetCustomerDashboardDataResponse
     */
    users_ids_and_metadata?: Array<GetCustomerDashboardDataResponseUsersIdsAndMetadata>;

    /**
     * The number of customer users
     *
     * @type {number}
     * @memberof GetCustomerDashboardDataResponse
     * @example 10
     */
    count?: number;

    /**
     * The average quality of the customer users in percent
     *
     * @type {number}
     * @memberof GetCustomerDashboardDataResponse
     * @example 71.25
     */
    average_users_quality?: number;

    /**
     * The average match relevance in percent
     *
     * @type {number}
     * @memberof GetCustomerDashboardDataResponse
     * @example 48.85
     */
    average_match_relevance?: number;

    /**
     * The average match relevance for accurate matches in percent
     *
     * @type {number}
     * @memberof GetCustomerDashboardDataResponse
     * @example 68.25
     */
    average_match_relevance_accurate?: number;
}
