/* tslint:disable */
/* eslint-disable */
/**
 * Apimg
 * Apimg's API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface GetCustomerUserDetailsResponseUsers
 */
export interface GetCustomerUserDetailsResponseUsers {

    /**
     * @type {string}
     * @memberof GetCustomerUserDetailsResponseUsers
     * @example 1-12
     */
    id?: string;

    /**
     * @type {number}
     * @memberof GetCustomerUserDetailsResponseUsers
     * @example 1
     */
    customer_id?: number;

    /**
     * The ID of the customer user in the user database
     *
     * @type {string}
     * @memberof GetCustomerUserDetailsResponseUsers
     * @example UUID_1234
     */
    id_customer_db?: string;

    /**
     * Geolocation coordinates
     *
     * @type {Array<number>}
     * @memberof GetCustomerUserDetailsResponseUsers
     * @example [48.8566,2.3522]
     */
    geolocation?: Array<number>;

    /**
     * @type {string}
     * @memberof GetCustomerUserDetailsResponseUsers
     * @example 1990-01-01
     */
    birthday?: string | null;

    /**
     * @type {Array<string>}
     * @memberof GetCustomerUserDetailsResponseUsers
     * @example ["1-1-3-0","1-1-3-1"]
     */
    categories_items?: Array<string>;

    /**
     * @type {{ [key: string]: string; }}
     * @memberof GetCustomerUserDetailsResponseUsers
     * @example {}
     */
    filters?: { [key: string]: string; };

    /**
     * @type {{ [key: string]: string; }}
     * @memberof GetCustomerUserDetailsResponseUsers
     * @example {}
     */
    other_subcategories_comparisons?: { [key: string]: string; };

    /**
     * @type {string}
     * @memberof GetCustomerUserDetailsResponseUsers
     * @example 1-3
     */
    profile_type?: string;

    /**
     * @type {{ [key: string]: string; }}
     * @memberof GetCustomerUserDetailsResponseUsers
     * @example {"email":"us1@example.com","firstname":"Alexander","lastname":"Hamilton"}
     */
    metadata?: { [key: string]: string; } | null;

    /**
     * @type {Date}
     * @memberof GetCustomerUserDetailsResponseUsers
     * @example 2024-09-21T14:44:53.789Z
     */
    created_at?: Date;

    /**
     * @type {Date}
     * @memberof GetCustomerUserDetailsResponseUsers
     * @example 2024-09-21T14:44:53.789Z
     */
    updated_at?: Date;

    /**
     * @type {number}
     * @memberof GetCustomerUserDetailsResponseUsers
     * @example 12
     */
    index?: number;
}
