/* tslint:disable */
/* eslint-disable */
/**
 * Apimg
 * Apimg's API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface GetCustomerUserItemsResponseUsers
 */
export interface GetCustomerUserItemsResponseUsers {

    /**
     * The ID of the customer user in its DB
     *
     * @type {string}
     * @memberof GetCustomerUserItemsResponseUsers
     * @example UUID_1234
     */
    user_id?: string;

    /**
     * @type {{ [key: string]: { [key: string]: Array<string>; }; }}
     * @memberof GetCustomerUserItemsResponseUsers
     */
    items?: { [key: string]: { [key: string]: Array<string>; }; };

    /**
     * @type {Array<number>}
     * @memberof GetCustomerUserItemsResponseUsers
     * @example [48.8566,2.3522]
     */
    geolocation?: Array<number>;

    /**
     * @type {{ [key: string]: boolean | Array<number> | Array<string>; }}
     * @memberof GetCustomerUserItemsResponseUsers
     * @example {"subcategory1":true,"subcategory2":[1,2,3],"subcategory3":["item1","item2"]}
     */
    other_subcategories_comparisons?: { [key: string]: boolean | Array<number> | Array<string>; };
}
