/* tslint:disable */
/* eslint-disable */
/**
 * Apimg
 * Apimg's API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * Request body to retrieve multiple customer user details
 *
 * @export
 * @interface GetMultipleCustomerUserDetailsRequest
 */
export interface GetMultipleCustomerUserDetailsRequest {

    /**
     * List of customer user IDs from the user DB to retrieve details for
     *
     * @type {Array<string>}
     * @memberof GetMultipleCustomerUserDetailsRequest
     * @example ["UUID_1234","UUID_5678"]
     */
    users_ids: Array<string>;
}
