/* tslint:disable */
/* eslint-disable */
/**
 * Apimg
 * Apimg's API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { GetCustomerDetailsResponseCustomer } from './get-customer-details-response-customer';
 /**
 * Response body for customer details
 *
 * @export
 * @interface GetCustomerDetailsResponse
 */
export interface GetCustomerDetailsResponse {

    /**
     * @type {GetCustomerDetailsResponseCustomer}
     * @memberof GetCustomerDetailsResponse
     */
    customer?: GetCustomerDetailsResponseCustomer;
}
