/* tslint:disable */
/* eslint-disable */
/**
 * Apimg
 * Apimg's API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * Request body to get discriminating criterion results
 *
 * @export
 * @interface GetDiscriminatingCriterionRequest
 */
export interface GetDiscriminatingCriterionRequest {

    /**
     * The user ID that you specified when registering the user, must be a string
     *
     * @type {string}
     * @memberof GetDiscriminatingCriterionRequest
     * @example user-123
     */
    userId: string;
}
