/* tslint:disable */
/* eslint-disable */
/**
 * Apimg
 * Apimg's API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * The matching usage of the user
 *
 * @export
 * @interface GetCustomerDetailsResponseCustomerMatchingUsage
 */
export interface GetCustomerDetailsResponseCustomerMatchingUsage {

    /**
     * @type {number}
     * @memberof GetCustomerDetailsResponseCustomerMatchingUsage
     * @example 1986
     */
    all?: number;

    /**
     * @type {number}
     * @memberof GetCustomerDetailsResponseCustomerMatchingUsage
     * @example 1370
     */
    current_year?: number;

    /**
     * @type {number}
     * @memberof GetCustomerDetailsResponseCustomerMatchingUsage
     * @example 3
     */
    current_month?: number;
}
