/* tslint:disable */
/* eslint-disable */
/**
 * Apimg
 * Apimg's API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * Response body for matching settings
 *
 * @export
 * @interface GetMatchingSettingsResponse
 */
export interface GetMatchingSettingsResponse {

    /**
     * The matching gauge value in percent
     *
     * @type {number}
     * @memberof GetMatchingSettingsResponse
     * @example 20
     */
    matching_gauge?: number;

    /**
     * The cosine similarity gauge value in percent
     *
     * @type {number}
     * @memberof GetMatchingSettingsResponse
     * @example 60
     */
    cosine_similarity_gauge?: number;

    /**
     * The cosine similarity gauge for cross criterions value in percent
     *
     * @type {number}
     * @memberof GetMatchingSettingsResponse
     * @example 60
     */
    cosine_similarity_cross_criterions_gauge?: number;

    /**
     * Option to allow already seen results
     *
     * @type {boolean}
     * @memberof GetMatchingSettingsResponse
     * @example true
     */
    allow_already_seen?: boolean;

    /**
     * Links between user profile types, which profile type ID can see which other profile types IDs ?
     *
     * @type {{ [key: string]: Array<string> | Map; }}
     * @memberof GetMatchingSettingsResponse
     * @example {"1-1":["1-2","1-3"],"1-2":{"network 1":["1-1"],"network 2":["1-2","1-3"]}}
     */
    user_profile_type_links?: { [key: string]: Array<string> | Map; };
}
