/* tslint:disable */
/* eslint-disable */
/**
 * Apimg
 * Apimg's API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * Response body for API key
 *
 * @export
 * @interface GetApiKeyResponse
 */
export interface GetApiKeyResponse {

    /**
     * The API key for the customer.
     *
     * @type {string}
     * @memberof GetApiKeyResponse
     * @example your-api-key
     */
    apiKey?: string;
}
