/* tslint:disable */
/* eslint-disable */
/**
 * Apimg
 * Apimg's API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { GetCustomerUserDetailsResponseUsers } from './get-customer-user-details-response-users';
 /**
 * Response body for multiple customer user details
 *
 * @export
 * @interface GetMultipleCustomerUserDetailsResponse
 */
export interface GetMultipleCustomerUserDetailsResponse {

    /**
     * @type {Array<GetCustomerUserDetailsResponseUsers>}
     * @memberof GetMultipleCustomerUserDetailsResponse
     */
    users?: Array<GetCustomerUserDetailsResponseUsers>;
}
