/* tslint:disable */
/* eslint-disable */
/**
 * Apimg
 * Apimg's API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * List of the last 10 suggested matchs
 *
 * @export
 * @interface GetCustomerDashboardDataResponseLastSuggestedMatchs
 */
export interface GetCustomerDashboardDataResponseLastSuggestedMatchs {

    /**
     * @type {string}
     * @memberof GetCustomerDashboardDataResponseLastSuggestedMatchs
     */
    user_id?: string;

    /**
     * @type {string}
     * @memberof GetCustomerDashboardDataResponseLastSuggestedMatchs
     */
    match_id?: string;
}
