/* tslint:disable */
/* eslint-disable */
/**
 * Apimg
 * Apimg's API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { GetCustomerUserItemsResponseUsers } from './get-customer-user-items-response-users';
 /**
 * Response body for customer users items
 *
 * @export
 * @interface GetCustomerUserItemsResponse
 */
export interface GetCustomerUserItemsResponse {

    /**
     * @type {Array<GetCustomerUserItemsResponseUsers>}
     * @memberof GetCustomerUserItemsResponse
     */
    users?: Array<GetCustomerUserItemsResponseUsers>;
}
