/* tslint:disable */
/* eslint-disable */
/**
 * Apimg
 * Apimg's API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * Request body to retrieve customer users profile types
 *
 * @export
 * @interface GetCustomerUsersProfileTypesRequest
 */
export interface GetCustomerUsersProfileTypesRequest {

    /**
     * List of user IDs to retrieve profile types for
     *
     * @type {Array<number>}
     * @memberof GetCustomerUsersProfileTypesRequest
     * @example [1,2,3]
     */
    users_ids: Array<number>;
}
