/* tslint:disable */
/* eslint-disable */
/**
 * Apimg
 * Apimg's API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * Response body for discriminating criterion results
 *
 * @export
 * @interface GetDiscriminatingCriterionResponse
 */
export interface GetDiscriminatingCriterionResponse {

    /**
     * @type {string}
     * @memberof GetDiscriminatingCriterionResponse
     * @example 1-13
     */
    category_id?: string;

    /**
     * @type {string}
     * @memberof GetDiscriminatingCriterionResponse
     * @example 1-13-1
     */
    subcategory_id?: string;
}
