/* tslint:disable */
/* eslint-disable */
/**
 * Apimg
 * Apimg's API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * Response body for Access Token
 *
 * @export
 * @interface GetAccessTokenResponse
 */
export interface GetAccessTokenResponse {

    /**
     * The Access Token.
     *
     * @type {string}
     * @memberof GetAccessTokenResponse
     * @example your-access-token
     */
    accessToken?: string;

    /**
     * When will the Access Token expire (generation datetime + 18 hours).
     *
     * @type {number}
     * @memberof GetAccessTokenResponse
     * @example 1742457751
     */
    accessTokenExpireAt?: number;

    /**
     * The renewed Refresh Token.
     *
     * @type {string}
     * @memberof GetAccessTokenResponse
     * @example your-renewed-refresh-token
     */
    refreshToken?: string;

    /**
     * When will the Refresh Token expire (generation datetime + 90 days).
     *
     * @type {number}
     * @memberof GetAccessTokenResponse
     * @example 1750168951
     */
    refreshTokenExpireAt?: number;
}
