/* tslint:disable */
/* eslint-disable */
/**
 * Apimg
 * Apimg's API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * List of the customer user IDs and their profile type and metadata
 *
 * @export
 * @interface GetCustomerDashboardDataResponseUsersIdsAndMetadata
 */
export interface GetCustomerDashboardDataResponseUsersIdsAndMetadata {

    /**
     * @type {string}
     * @memberof GetCustomerDashboardDataResponseUsersIdsAndMetadata
     */
    user_id?: string;

    /**
     * @type {string}
     * @memberof GetCustomerDashboardDataResponseUsersIdsAndMetadata
     */
    profile_type?: string;

    /**
     * @type {{ [key: string]: string; }}
     * @memberof GetCustomerDashboardDataResponseUsersIdsAndMetadata
     */
    metadata?: { [key: string]: string; } | null;
}
