/* tslint:disable */
/* eslint-disable */
/**
 * Apimg
 * Apimg's API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Category2 } from './category2';
import { Item1 } from './item1';
import { Subcategory6 } from './subcategory6';
 /**
 * Response body for customer algorithm categories, subcategories, and items
 *
 * @export
 * @interface GetCustomerAlgorithmCategoriesSubcategoriesItemsResponse
 */
export interface GetCustomerAlgorithmCategoriesSubcategoriesItemsResponse {

    /**
     * List of categories
     *
     * @type {Array<Category2>}
     * @memberof GetCustomerAlgorithmCategoriesSubcategoriesItemsResponse
     */
    categories?: Array<Category2>;

    /**
     * List of subcategories
     *
     * @type {Array<Subcategory6>}
     * @memberof GetCustomerAlgorithmCategoriesSubcategoriesItemsResponse
     */
    subcategories?: Array<Subcategory6>;

    /**
     * List of items
     *
     * @type {Array<Item1>}
     * @memberof GetCustomerAlgorithmCategoriesSubcategoriesItemsResponse
     */
    items?: Array<Item1>;

    /**
     * Indicates if geolocation is enabled
     *
     * @type {boolean}
     * @memberof GetCustomerAlgorithmCategoriesSubcategoriesItemsResponse
     * @example true
     */
    hasGeolocation?: boolean;
}
