/* tslint:disable */
/* eslint-disable */
/**
 * Apimg
 * Apimg's API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { GetCustomerDashboardDataResponseTopsLowestQualityUsers } from './get-customer-dashboard-data-response-tops-lowest-quality-users';
 /**
 * 
 *
 * @export
 * @interface GetCustomerDashboardDataResponseTops
 */
export interface GetCustomerDashboardDataResponseTops {

    /**
     * List of the 10 most proposed customer user IDs
     *
     * @type {Array<string>}
     * @memberof GetCustomerDashboardDataResponseTops
     */
    most_proposed_ids?: Array<string>;

    /**
     * @type {Array<string>}
     * @memberof GetCustomerDashboardDataResponseTops
     */
    monthly_api_calls?: Array<string>;

    /**
     * List of the 5 lowest quality customer users
     *
     * @type {Array<GetCustomerDashboardDataResponseTopsLowestQualityUsers>}
     * @memberof GetCustomerDashboardDataResponseTops
     */
    lowest_quality_users?: Array<GetCustomerDashboardDataResponseTopsLowestQualityUsers>;
}
