/* tslint:disable */
/* eslint-disable */
/**
 * Apimg
 * Apimg's API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface GetCustomerDashboardDataResponseTopsLowestQualityUsers
 */
export interface GetCustomerDashboardDataResponseTopsLowestQualityUsers {

    /**
     * @type {string}
     * @memberof GetCustomerDashboardDataResponseTopsLowestQualityUsers
     */
    user_id?: string;

    /**
     * @type {number}
     * @memberof GetCustomerDashboardDataResponseTopsLowestQualityUsers
     */
    quality_percent?: number;
}
