/* tslint:disable */
/* eslint-disable */
/**
 * Apimg
 * Apimg's API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { GetCustomerDetailsResponseCustomerMatchingUsage } from './get-customer-details-response-customer-matching-usage';
 /**
 * 
 *
 * @export
 * @interface GetCustomerDetailsResponseCustomer
 */
export interface GetCustomerDetailsResponseCustomer {

    /**
     * @type {string}
     * @memberof GetCustomerDetailsResponseCustomer
     * @example customer@example.com
     */
    email?: string;

    /**
     * @type {string}
     * @memberof GetCustomerDetailsResponseCustomer
     * @example MyCompany
     */
    name?: string;

    /**
     * @type {string}
     * @memberof GetCustomerDetailsResponseCustomer
     * @example My company is a great company
     */
    description?: string | null;

    /**
     * @type {string}
     * @memberof GetCustomerDetailsResponseCustomer
     * @example MyApp
     */
    website_app_name?: string | null;

    /**
     * @type {string}
     * @memberof GetCustomerDetailsResponseCustomer
     * @example https://www.myCompany.fr
     */
    website_url?: string | null;

    /**
     * @type {GetCustomerDetailsResponseCustomerMatchingUsage}
     * @memberof GetCustomerDetailsResponseCustomer
     */
    matching_usage?: GetCustomerDetailsResponseCustomerMatchingUsage;

    /**
     * The user ID
     *
     * @type {number}
     * @memberof GetCustomerDetailsResponseCustomer
     * @example 1
     */
    id?: number;
}
