/* tslint:disable */
/* eslint-disable */
/**
 * Apimg
 * Apimg's API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface InlineResponse2001
 */
export interface InlineResponse2001 {

    /**
     * The unique identifier for the item
     *
     * @type {string}
     * @memberof InlineResponse2001
     * @example 1-1-1-1
     */
    id?: string;

    /**
     * The name of the item
     *
     * @type {string}
     * @memberof InlineResponse2001
     * @example Nouvelle Aquitaine
     */
    item_name?: string;

    /**
     * Comparison with other items
     *
     * @type {{ [key: string]: number; }}
     * @memberof InlineResponse2001
     * @example {"1-1-1-2":2,"1-1-1-3":3}
     */
    compare_with?: { [key: string]: number; } | null;
}
