/* tslint:disable */
/* eslint-disable */
/**
 * Apimg
 * Apimg's API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * Internal server error response
 *
 * @export
 * @interface InternalServerError
 */
export interface InternalServerError {

    /**
     * @type {string}
     * @memberof InternalServerError
     * @example Internal server error
     */
    error?: string;
}
