/* tslint:disable */
/* eslint-disable */
/**
 * Apimg
 * Apimg's API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { V1customerAlgorithmitemsmatchesItem } from './v1customer-algorithmitemsmatches-item';
import { V1customerAlgorithmitemsmatchesMatches } from './v1customer-algorithmitemsmatches-matches';
 /**
 * Item matches content
 *
 * @export
 * @interface ItemMatches
 */
export interface ItemMatches {

    /**
     * @type {V1customerAlgorithmitemsmatchesItem}
     * @memberof ItemMatches
     */
    item?: V1customerAlgorithmitemsmatchesItem;

    /**
     * @type {Array<V1customerAlgorithmitemsmatchesMatches>}
     * @memberof ItemMatches
     */
    matches?: Array<V1customerAlgorithmitemsmatchesMatches>;
}
