/* tslint:disable */
/* eslint-disable */
/**
 * Apimg
 * Apimg's API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * Response body for login
 *
 * @export
 * @interface LoginResponse
 */
export interface LoginResponse {

    /**
     * JWT token for the authenticated customer
     *
     * @type {string}
     * @memberof LoginResponse
     * @example aaaa.bbbb.cccc
     */
    token?: string;
}
