/* tslint:disable */
/* eslint-disable */
/**
 * Apimg
 * Apimg's API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * Request body to log in
 *
 * @export
 * @interface LoginRequest
 */
export interface LoginRequest {

    /**
     * The email address
     *
     * @type {string}
     * @memberof LoginRequest
     * @example customer@example.com
     */
    email: string;

    /**
     * The password
     *
     * @type {string}
     * @memberof LoginRequest
     * @example password123
     */
    password: string;
}
