/* tslint:disable */
/* eslint-disable */
/**
 * Apimg
 * Apimg's API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * Client error response for invalid request
 *
 * @export
 * @interface RequestClientError
 */
export interface RequestClientError {

    /**
     * The error code
     *
     * @type {string}
     * @memberof RequestClientError
     * @example INCORRECT_JSON
     */
    code?: string;

    /**
     * @type {string}
     * @memberof RequestClientError
     * @example ClientError
     */
    name?: string;

    /**
     * The error reason
     *
     * @type {string}
     * @memberof RequestClientError
     * @example Le body de la requête est incorrect
     */
    message?: string;

    /**
     * The error details
     *
     * @type {Array<string>}
     * @memberof RequestClientError
     */
    details?: Array<string>;
}
