/* tslint:disable */
/* eslint-disable */
/**
 * Apimg
 * Apimg's API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * Response body for signup
 *
 * @export
 * @interface SignupResponse
 */
export interface SignupResponse {

    /**
     * JWT token for the authenticated customer
     *
     * @type {string}
     * @memberof SignupResponse
     * @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzI2OTI0MTkzLCJleHAiOjE3MjY5ODg5OTN9.aHPOnxlOlL92DTGn6mRbllJX0m193xRVs4np0mEM_FM
     */
    token?: string;
}
