/* tslint:disable */
/* eslint-disable */
/**
 * Apimg
 * Apimg's API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * Request body to sign up
 *
 * @export
 * @interface SignupRequest
 */
export interface SignupRequest {

    /**
     * The email address
     *
     * @type {string}
     * @memberof SignupRequest
     * @example customer@example.com
     */
    email: string;

    /**
     * The password
     *
     * @type {string}
     * @memberof SignupRequest
     * @example password123
     */
    password: string;

    /**
     * The name of the user's company
     *
     * @type {string}
     * @memberof SignupRequest
     * @example My Company
     */
    name: string;

    /**
     * The description of the user's company
     *
     * @type {string}
     * @memberof SignupRequest
     * @example My company is a great company
     */
    description?: string;

    /**
     * The name of the user's company website or app
     *
     * @type {string}
     * @memberof SignupRequest
     * @example MyApp
     */
    website_app_name?: string;

    /**
     * The URL of the user's company's website
     *
     * @type {string}
     * @memberof SignupRequest
     * @example https://www.myCompany.fr
     */
    website_url?: string;
}
