/* tslint:disable */
/* eslint-disable */
/**
 * Apimg
 * Apimg's API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * Subcategory request item
 *
 * @export
 * @interface SubcategoryRequestItem
 */
export interface SubcategoryRequestItem {

    /**
     * The ID of the category to which the subcategory belongs (optional)
     *
     * @type {string}
     * @memberof SubcategoryRequestItem
     * @example 1-12
     */
    category_id?: string;

    /**
     * The name of the subcategory
     *
     * @type {string}
     * @memberof SubcategoryRequestItem
     * @example Subcategory 1
     */
    name?: string;

    /**
     * The level number (weight) of the subcategory
     *
     * @type {number}
     * @memberof SubcategoryRequestItem
     * @example 1
     */
    level_number?: number;

    /**
     * The type of subcategory, can be \"geolocation\" if the subcategory is used for geolocation, or \"other\" if not
     *
     * @type {string}
     * @memberof SubcategoryRequestItem
     * @example other
     */
    type?: SubcategoryRequestItemTypeEnum;

    /**
     * The maximum distance in meter allowed, 0 means no distance limit
     *
     * @type {number}
     * @memberof SubcategoryRequestItem
     * @example 1000000
     */
    max_distance_allowed_meters?: number;
}

/**
 * @export
 * @enum {string}
 */
export enum SubcategoryRequestItemTypeEnum {
    Geolocation = 'geolocation',
    Other = 'other'
}

