/* tslint:disable */
/* eslint-disable */
/**
 * Apimg
 * Apimg's API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * Subcategory content
 *
 * @export
 * @interface Subcategory1
 */
export interface Subcategory1 {

    /**
     * The unique identifier for the subcategory
     *
     * @type {string}
     * @memberof Subcategory1
     * @example 1-1-1
     */
    id?: string;

    /**
     * The name of the subcategory
     *
     * @type {string}
     * @memberof Subcategory1
     * @example Région
     */
    subcategory_name?: string;

    /**
     * The level number (weight) of the subcategory
     *
     * @type {number}
     * @memberof Subcategory1
     * @example 5
     */
    level_number?: number;

    /**
     * The base score for the subcategory (optional)
     *
     * @type {number}
     * @memberof Subcategory1
     * @example 100
     */
    base_score?: number | null;

    /**
     * The type of the subcategory
     *
     * @type {number}
     * @memberof Subcategory1
     * @example 1
     */
    type?: number;

    /**
     * The ID of the paired subcategory (optional)
     *
     * @type {string}
     * @memberof Subcategory1
     * @example 1-1-2
     */
    paired_subcategory?: string | null;

    /**
     * Comparison with other subcategories and their respective level number (weight)s (optional)
     *
     * @type {{ [key: string]: number; }}
     * @memberof Subcategory1
     * @example {"1-1-3":2,"1-1-4":3}
     */
    compare_with?: { [key: string]: number; } | null;
}
