/* tslint:disable */
/* eslint-disable */
/**
 * Apimg
 * Apimg's API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * Subcategory content
 *
 * @export
 * @interface Subcategory5
 */
export interface Subcategory5 {

    /**
     * The unique identifier for the subcategory
     *
     * @type {string}
     * @memberof Subcategory5
     * @example 1-1-1
     */
    id?: string;

    /**
     * The name of the subcategory
     *
     * @type {string}
     * @memberof Subcategory5
     * @example Geolocation
     */
    subcategory_name?: string;

    /**
     * The level number (weight) of the subcategory
     *
     * @type {number}
     * @memberof Subcategory5
     * @example 0
     */
    level_number?: number;

    /**
     * The base score for the subcategory, (optional)
     *
     * @type {number}
     * @memberof Subcategory5
     */
    base_score?: number | null;

    /**
     * The type of subcategory (1 for \"other\", 2 for \"geolocation\")
     *
     * @type {number}
     * @memberof Subcategory5
     * @example 2
     */
    type?: Subcategory5TypeEnum;

    /**
     * The maximum distance in meter allowed, 0 means no distance limit
     *
     * @type {number}
     * @memberof Subcategory5
     * @example 1000000
     */
    max_distance_allowed?: number | null;

    /**
     * The ID of the paired subcategory (optional)
     *
     * @type {string}
     * @memberof Subcategory5
     */
    paired_subcategory?: string | null;

    /**
     * Comparison with other subcategories and their respective level number (weight)s (optional)
     *
     * @type {{ [key: string]: number; }}
     * @memberof Subcategory5
     */
    compare_with?: { [key: string]: number; } | null;
}

/**
 * @export
 * @enum {string}
 */
export enum Subcategory5TypeEnum {
    NUMBER_1 = 1,
    NUMBER_2 = 2
}

