/* tslint:disable */
/* eslint-disable */
/**
 * Apimg
 * Apimg's API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * Subcategory content
 *
 * @export
 * @interface Subcategory
 */
export interface Subcategory {

    /**
     * The subcategory ID
     *
     * @type {string}
     * @memberof Subcategory
     * @example 1-12-1
     */
    id?: string;

    /**
     * The name of the subcategory
     *
     * @type {string}
     * @memberof Subcategory
     * @example Subcategory 1
     */
    subcategory_name?: string;

    /**
     * The level number (weight) of the subcategory
     *
     * @type {number}
     * @memberof Subcategory
     * @example 1
     */
    level_number?: number;

    /**
     * The base score, used for geolocation
     *
     * @type {number}
     * @memberof Subcategory
     * @example 50
     */
    base_score?: number | null;

    /**
     * The type of subcategory
     *
     * @type {number}
     * @memberof Subcategory
     * @example 1
     */
    type?: number;

    /**
     * The ID of the paired subcategory (to which subcategory we must compare this subcategory)
     *
     * @type {string}
     * @memberof Subcategory
     * @example 1-12-2
     */
    paired_subcategory?: string | null;

    /**
     * Comparison with other subcategories
     *
     * @type {{ [key: string]: number; }}
     * @memberof Subcategory
     * @example {"1-12-3":2,"1-12-4":3}
     */
    compare_with?: { [key: string]: number; } | null;
}
