/* tslint:disable */
/* eslint-disable */
/**
 * Apimg
 * Apimg's API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * Subcategory name content
 *
 * @export
 * @interface SubcategoryName
 */
export interface SubcategoryName {

    /**
     * The unique identifier for the subcategory
     *
     * @type {string}
     * @memberof SubcategoryName
     * @example 1-1-1
     */
    id?: string;

    /**
     * The new name of the subcategory
     *
     * @type {string}
     * @memberof SubcategoryName
     * @example State
     */
    name?: string;
}
