/* tslint:disable */
/* eslint-disable */
/**
 * Apimg
 * Apimg's API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * Subcategory compare with content
 *
 * @export
 * @interface SubcategoryCompareWith
 */
export interface SubcategoryCompareWith {

    /**
     * The unique identifier for the subcategory
     *
     * @type {string}
     * @memberof SubcategoryCompareWith
     * @example 1-1-1
     */
    id?: string;

    /**
     * Comparison with other subcategories
     *
     * @type {{ [key: string]: number; }}
     * @memberof SubcategoryCompareWith
     * @example {"1-1-2":2,"1-1-3":3}
     */
    compare_with?: { [key: string]: number; } | null;
}
