/* tslint:disable */
/* eslint-disable */
/**
 * Apimg
 * Apimg's API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { V1customerAlgorithmitemsnameItems } from './v1customer-algorithmitemsname-items';
 /**
 * Request body to update customer items name
 *
 * @export
 * @interface UpdateCustomerItemsNameRequest
 */
export interface UpdateCustomerItemsNameRequest {

    /**
     * List of subcategories to update
     *
     * @type {Array<V1customerAlgorithmitemsnameItems>}
     * @memberof UpdateCustomerItemsNameRequest
     */
    items: Array<V1customerAlgorithmitemsnameItems>;
}
