/* tslint:disable */
/* eslint-disable */
/**
 * Apimg
 * Apimg's API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * Request body to update customer geolocation subcategory values
 *
 * @export
 * @interface UpdateCustomerSubcategoryGeolocationValues
 */
export interface UpdateCustomerSubcategoryGeolocationValues {

    /**
     * The maximum distance in meter allowed, 0 means no distance limit
     *
     * @type {number}
     * @memberof UpdateCustomerSubcategoryGeolocationValues
     * @example 1000000
     */
    max_distance_allowed_meters: number;
}
