/* tslint:disable */
/* eslint-disable */
/**
 * Apimg
 * Apimg's API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ItemCompareWith } from './item-compare-with';
 /**
 * Request body to update customer items compare with array
 *
 * @export
 * @interface UpdateCustomerItemsCompareWithRequest
 */
export interface UpdateCustomerItemsCompareWithRequest {

    /**
     * List of changes to be made to the compare with array
     *
     * @type {Array<ItemCompareWith>}
     * @memberof UpdateCustomerItemsCompareWithRequest
     */
    changes: Array<ItemCompareWith>;
}
