/* tslint:disable */
/* eslint-disable */
/**
 * Apimg
 * Apimg's API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { CategoryWeight } from './category-weight';
 /**
 * Request body to update customer categories level number (weight)
 *
 * @export
 * @interface UpdateCustomerCategoriesWeightRequest
 */
export interface UpdateCustomerCategoriesWeightRequest {

    /**
     * List of changes to be made to the level numbers (weight)
     *
     * @type {Array<CategoryWeight>}
     * @memberof UpdateCustomerCategoriesWeightRequest
     */
    changes: Array<CategoryWeight>;
}
