/* tslint:disable */
/* eslint-disable */
/**
 * Apimg
 * Apimg's API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { SubcategoryName } from './subcategory-name';
 /**
 * Request body to update customer subcategories name
 *
 * @export
 * @interface UpdateCustomerSubcategoriesNameRequest
 */
export interface UpdateCustomerSubcategoriesNameRequest {

    /**
     * List of subcategories to update
     *
     * @type {Array<SubcategoryName>}
     * @memberof UpdateCustomerSubcategoriesNameRequest
     */
    items: Array<SubcategoryName>;
}
