/* tslint:disable */
/* eslint-disable */
/**
 * Apimg
 * Apimg's API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * User profile type content
 *
 * @export
 * @interface UserProfileType
 */
export interface UserProfileType {

    /**
     * The user profile type ID
     *
     * @type {string}
     * @memberof UserProfileType
     * @example 1-2
     */
    id?: string;

    /**
     * The name of the user profile type
     *
     * @type {string}
     * @memberof UserProfileType
     * @example Agency
     */
    type?: string;

    /**
     * List of category IDs used by the profile type
     *
     * @type {Array<string>}
     * @memberof UserProfileType
     * @example ["1-12-1","1-12-2"]
     */
    used_categories?: Array<string>;
}
