/* tslint:disable */
/* eslint-disable */
/**
 * Apimg
 * Apimg's API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface V1customerAlgorithmitemsnameItems
 */
export interface V1customerAlgorithmitemsnameItems {

    /**
     * The unique identifier for the item
     *
     * @type {string}
     * @memberof V1customerAlgorithmitemsnameItems
     * @example 1-1-1-1
     */
    id?: string;

    /**
     * The new name of the item
     *
     * @type {string}
     * @memberof V1customerAlgorithmitemsnameItems
     * @example Aquitaine
     */
    name?: string;
}
