/* tslint:disable */
/* eslint-disable */
/**
 * Apimg
 * Apimg's API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface V1customerAlgorithmitemsmatchesItem
 */
export interface V1customerAlgorithmitemsmatchesItem {

    /**
     * @type {string}
     * @memberof V1customerAlgorithmitemsmatchesItem
     * @example 1-1-1-219
     */
    id?: string;

    /**
     * @type {string}
     * @memberof V1customerAlgorithmitemsmatchesItem
     * @example SEO referencing
     */
    item_name?: string;
}
