/* tslint:disable */
/* eslint-disable */
/**
 * Apimg
 * Apimg's API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface V1customeruserUsers
 */
export interface V1customeruserUsers {

    /**
     * The ID of the customer user in the user database
     *
     * @type {string}
     * @memberof V1customeruserUsers
     * @example UUID_1234
     */
    id_customer_db?: string;

    /**
     * the category id of the customer user
     *
     * @type {string}
     * @memberof V1customeruserUsers
     * @example if the user is an admin and admin category's id is '1-3', you must then set '1-3' as value
     */
    profile_type?: string;

    /**
     * Birthday in yyyy-mm-dd or ISO format
     *
     * @type {string}
     * @memberof V1customeruserUsers
     * @example 1990-01-01 or 1990-01-01T00:00:00.000Z
     */
    birthday?: string;

    /**
     * Geolocation coordinates
     *
     * @type {Array<number>}
     * @memberof V1customeruserUsers
     * @example [48.8566,2.3522]
     */
    geolocation?: Array<number>;

    /**
     * List of category items ids to associate to the user
     *
     * @type {Array<string>}
     * @memberof V1customeruserUsers
     * @example ["1-1-23-1","1-1-23-2"]
     */
    categories_items?: Array<string>;

    /**
     * Subcategory comparisons - let empty for now
     *
     * @type {any}
     * @memberof V1customeruserUsers
     * @example {}
     */
    other_subcategories_comparisons?: any;

    /**
     * Filters - let empty for now
     *
     * @type {any}
     * @memberof V1customeruserUsers
     * @example {}
     */
    filters?: any;

    /**
     * Metadata
     *
     * @type {{ [key: string]: string; }}
     * @memberof V1customeruserUsers
     * @example {"email":"u1@example.com","firstname":"Alexander","lastname":"Hamilton"}
     */
    metadata?: { [key: string]: string; } | null;
}
